
export const ALL_CLIENTS_SUCCESS = 'ALL_CLIENTS_SUCCESS'
export const SINGLE_CLIENT_SUCCESS = 'SINGLE_CLIENT_SUCCESS'
export const ALL_CANDIDATES_SUCCESS = 'ALL_CANDIDATES_SUCCESS'
export const SINGLE_CANDIDATE_SUCCESS = 'SINGLE_CANDIDATE_SUCCESS'
export const ALL_APPLICATIONS_SUCCESS = 'ALL_APPLICATIONS_SUCCESS'
export const SINGLE_APPLICATION_SUCCESS = 'SINGLE_APPLICATION_SUCCESS'
export const PROJECTS_BY_CLIENT_SUCCESS = 'PROJECTS_BY_CLIENT_SUCCESS'
export const SINGLE_PROJECT_SUCCESS = 'SINGLE_PROJECT_SUCCESS'
export const CONTACTS_BY_CLIENT_SUCCESS = 'CONTACTS_BY_CLIENT_SUCCESS'
export const ALL_CITIES_SUCCESS = 'ALL_CITIES_SUCCESS'
export const BITCOIN_TRANSACTIONS_BY_CLIENT_SUCCESS = 'BITCOIN_TRANSACTIONS_BY_CLIENT_SUCCESS'
export const XGOLD_TRANSACTIONS_BY_CLIENT_SUCCESS = 'XGOLD_TRANSACTIONS_BY_CLIENT_SUCCESS'
export const COIN_PRICES_SUCCESS = 'COIN_PRICES_SUCCESS'
export const ALL_PACKAGES_SUCCESS = 'ALL_PACKAGES_SUCCESS'
export const SINGLE_PACKAGE_SUCCESS = 'SINGLE_PACKAGE_SUCCESS'

// Staff mutation types
export const ALL_USERS_SUCCESS = 'ALL_USERS_SUCCESS'
export const SINGLE_USER_SUCCESS = 'SINGLE_USER_SUCCESS'
export const CURRENT_USER_SUCCESS = 'CURRENT_USER_SUCCESS'
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'
export const ACCOUNT_BALANCE_SUCCESS = 'ACCOUNT_BALANCE_SUCCESS'

// Settings mutation types
export const ALL_ROLES_SUCCESS = 'ALL_ROLES_SUCCESS'
export const ALL_SETTINGS_SUCCESS = 'ALL_SETTINGS_SUCCESS'
export const ALL_COUNTRIES_SUCCESS = 'ALL_COUNTRIES_SUCCESS'

// General mutation types
export const START_LOADING = 'START_LOADING'
export const STOP_LOADING = 'STOP_LOADING'
export const SUCCESS_MESSAGE = 'SUCCESS_MESSAGE'
export const ERROR_MESSAGE = 'ERROR_MESSAGE'
export const CONNECTION_ERROR_MESSAGE = 'CONNECTION_ERROR_MESSAGE'
export const HIDE_SHOW_MENUS = 'HIDE_SHOW_MENUS'