
export const ALL_CLIENTS_SUCCESS = 'ALL_CLIENTS_SUCCESS'
export const SINGLE_CLIENT_SUCCESS = 'SINGLE_CLIENT_SUCCESS'
export const ALL_LOANS_SUCCESS = 'ALL_LOANS_SUCCESS'
export const SINGLE_LOAN_SUCCESS = 'SINGLE_LOAN_SUCCESS'
export const LOAN_SCHEDULE_SUCCESS = 'LOAN_SCHEDULE_SUCCESS'

// Staff mutation types
export const ALL_USERS_SUCCESS = 'ALL_USERS_SUCCESS'
export const SINGLE_USER_SUCCESS = 'SINGLE_USER_SUCCESS'
export const CURRENT_USER_SUCCESS = 'CURRENT_USER_SUCCESS'
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'
export const ACCOUNT_BALANCE_SUCCESS = 'ACCOUNT_BALANCE_SUCCESS'

// Settings mutation types
export const ALL_ROLES_SUCCESS = 'ALL_ROLES_SUCCESS'
export const ALL_SETTINGS_SUCCESS = 'ALL_SETTINGS_SUCCESS'

// General mutation types
export const START_LOADING = 'START_LOADING'
export const STOP_LOADING = 'STOP_LOADING'
export const SUCCESS_MESSAGE = 'SUCCESS_MESSAGE'
export const ERROR_MESSAGE = 'ERROR_MESSAGE'
export const CONNECTION_ERROR_MESSAGE = 'CONNECTION_ERROR_MESSAGE'
export const HIDE_SHOW_MENUS = 'HIDE_SHOW_MENUS'