export default {
  clients: [],
  single_client: {},
  candidates: [],
  single_candidate: {},
  applications: [],
  single_application: {},
  projects: [],
  single_project: {},
  countries: [],
  // Staff
  users: [],
  single_user: {},
  current_user: {},
  account_balance: {},
  // Settings
  roles: [],
  settings: {},
  // Commons
  user: {},
  sex: [{name: 'Female'}, {name: 'Male'}],
  industries: [
    {name: 'Accounting'}, 
    {name: 'Agriculture'},
    {name: 'Banking'},
    {name: 'Capacity building'},
    {name: 'Construction/Real estate'},
    {name: 'Consulting'},
    {name: 'Customer service'},
    {name: 'Dairy/Fish industry'},
    {name: 'Education/Teaching'},
    {name: 'Engineering'},
    {name: 'Entertainment'},
    {name: 'Import/Export'},
    {name: 'Front office/Secretarial'},
    {name: 'Government'},
    {name: 'Hotels/Restaurants'},
    {name: 'HR/Admin/IR/Training'},
    {name: 'IT/Telcom'},
    {name: 'Legal'},
    {name: 'Manufacturing'},
    {name: 'Marketing/Sales'},
    {name: 'Mass Communication'},
    {name: 'Medical/Healthcare'},
    {name: 'NGO'},
    {name: 'Overseas/International'},
    {name: 'Procurement'},
    {name: 'Production/Operations'},
    {name: 'Project Management'},
    {name: 'Retailing'},
    {name: 'Security'},
    {name: 'Top management'},
    {name: 'Entertainment'},
    {name: 'Trading'},
    {name: 'Transportation/Logistics'},
    {name: 'Travel and Tourism'},
    {name: 'Other'},
  ],
  experiences: [
    {name: 'Fresher'}, 
    {name: '1'},
    {name: '2'},
    {name: '3'},
    {name: '4'},
    {name: '5'},
    {name: '6'},
    {name: '7'},
  ],
  levels: [
    {name: 'Fresher'}, 
    {name: 'Executive - Non-managerial'},
    {name: 'Executive - Managerial'},
    {name: 'Junior Management'},
    {name: 'Middle Management'},
    {name: 'Senior Management'},
    {name: 'Top Management'},
    {name: 'Non-managerial(junior)'},
    {name: 'Non-managerial(senior)'},
  ],
  job_types: [
    {name: 'Full time'}, 
    {name: 'Part time'},
    {name: 'Temporary'},
    {name: 'Contract'},
  ],
  menu_display: true,
  clipped: false,
  drawer: true,
  fixed: false,
  dialog: false,
  isLoading: false,
  errorMessage: '',
  successMessage: '',
  rules: {
    required: (value) => !!value || 'This field is required.',
    password: v => (v || '').match(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*(_|[^\w])).+$/) ||
          'Password must contain an upper case letter, a numeric character, and a special character',
    min: v => v.length >= 8 || 'Min 8 characters',
    max: v => v.length <= 160 || 'Maximum characters (160) exceeded! Extra characters may be truncated during sending',
    email: (value) => {
      const pattern = /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/
      return pattern.test(value) || 'Invalid e-mail.'
    }
  },
  rowsPerpage: [ 30, 75, 150, { 'text': 'All', 'value': -1 } ]
}